site_name: Docq - Private & Secure AI Knowledge Insight
site_url: https://docqai.github.io/docq
site_description: Docq offers self-hosted, private and secure AI for knowledge insight on your private data with minimal onboarding and operational effort.
site_author: Docq Contributors
copyright: Copyright &copy; 2023 Docq Contributors
site_dir: html
repo_name: docqai/docq
repo_url: https://github.com/docqai/docq

plugins:
  - search
  # - mkapi # doesn't work with python 3.11. project not maintained
  - awesome-pages
  - social
  - gen-files:
      scripts:
        - misc/gen_pages.py

markdown_extensions:
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - toc:
      permalink: true

extra:
  analytics:
    provider: google
    property: G-SML7XH761K

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: assets/logo.jpg
  favicon: assets/favicon.png
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: docq
      accent: light-green
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: light-green
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.tooltips
    - navigation.instant
    - navigation.indexes
    - navigation.sections

  icon:
    repo: fontawesome/brands/github-alt
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

nav:
  - "Home": index.md
  - "Overview":
      - "Introduction": overview/introduction.md
      - "Design Principles": overview/design-principles.md
      - "Key Features": overview/key-features.md
      - "Deployment Scenarios": overview/deployment-scenarios.md
  - "User Guides":
      - "Getting Started": user-guide/getting-started.md
      - "Deploy to Streamlit": user-guide/deploy-to-streamlit.md
      - "Deploy to Azure": user-guide/deploy-to-streamlit.md
      - "Deploy to AWS": user-guide/deploy-to-aws.md
      - "Deploy to GCP": user-guide/deploy-to-gcp.md
      - "Configure Spaces": user-guide/config-spaces.md
      - "Data Sources": user-guide/data-sources.md
      - "Usage": user-guide/usage.md
      - "FAQ": user-guide/faq.md
  - "Developer Guides":
      - "Getting Started": developer-guide/getting-started.md
      - "Architecture": developer-guide/architecture.md
      - "Contributing": developer-guide/contributing.md
      - "Extensions": developer-guide/extensions.md
      - "FAQ": developer-guide/faq.md
  #- ... | glob=readme.md
  #- ... | regex=scenarios/.+.md
  - API: mkapi/api/docq
  - Tests: mkapi/tests/tests
  - "Issues GitHub": https://github.com/docqai/docq/issues
  - "Discussions GitHub": https://github.com/docqai/docq/discussions
  - "Acknowledgement": acknowledgement.md
