site_name: Docq - Private & Secure AI Knowledge Insight
site_url: https://docqai.github.io/docq
site_description: Docq offers self-hosted, private and secure AI for knowledge insight on your private data with minimal onboarding and operational effort. 
site_author: Docq Contributors
copyright: Copyright &copy; 2023 Docq Contributors
site_dir: html
repo_name: docqai/docq
repo_url: https://github.com/docqai/docq

plugins:
  - search
  - mkapi
  - awesome-pages
  - social
  - gen-files:
      scripts:
        - misc/gen_pages.py

markdown_extensions:
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

theme:
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: green
    accent: light-green
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: green
    accent: light-green
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotate
  - content.tooltips

  icon:
    repo: fontawesome/brands/github-alt
  logo: assets/logo.jpg
  favicon: assets/favicon.png
  language: en


nav:
  - 'Home': index.md
  - 'Overview':
    - 'Introduction': overview/introduction.md
    - 'Design Principles': overview/design-principles.md
    - 'Key Features': overview/key-features.md
    - 'Deployment Scenarios': overview/deployment-scenarios.md
  - 'User Guide': 
    - 'Getting Started': user-guide/getting-started.md
    - 'Installation': user-guide/installation.md
    - 'Configuration': user-guide/configuration.md
    - 'Usage': user-guide/usage.md
    - 'FAQ': user-guide/faq.md
  - 'Developer Guide': 
    - 'Getting Started': developer-guide/getting-started.md
    - 'Architecture': developer-guide/architecture.md
    - 'Contributing': developer-guide/contributing.md
    - 'FAQ': developer-guide/faq.md
  - ... | glob=readme.md
  - ... | regex=scenarios/.+.md
  - API: mkapi/api/docq
  - Tests: mkapi/tests/tests
  - 'Issues GitHub': https://github.com/docqai/docq/issues
  - 'Discussions GitHub': https://github.com/docqai/docq/discussions
  - 'Acknowledgement': acknowledgement.md
