$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
model: azureml://registries/azureml-meta/models/Llama-2-7b-chat/versions/8
instance_type: Standard_NC12s_v3
instance_count: 1
request_settings:
  request_timeout_ms: 90000
  max_concurrent_requests_per_instance: 1
  max_queue_wait_ms: 1000
