name: Build and Publish Container Image
on:
  push:
    branches:
      #- main
      - infra/aws-deploy
    paths:
      - 'source/**'
      - 'web/**'
      - 'pyproject.toml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get app version
        run: 
          echo "VERSION=$(cat pyproject.toml | grep version | head -1 | awk -F= '{ print $2 }' | sed 's/["]//g')" >> $GITHUB_ENV
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          target: prod
          build-args: |
            TESTBUILD=false
            BUILDTAG=3.11-slim-buster
            BUILDPLATFORM=linux/amd64
            TARGET=prod
          tags: |
            ghcr.io/${github.repository}:latest
            ghcr.io/${github.repository}:$VERSION
          file: ./Dockerfile
